### ISSUE TITLE
Issue if the post text has spaces or maybe if the row go on new line.

### ISSUE THREAD

**Issue by PeopleInside** [justoverclockl/last-users-posts#1]
Hi, I installed the version 0.1.7 and this issue is not present.
On the version 0.2.3 is placed a PC smile (picture) if the post has text who goes on new line.

Version 0.17, text OK, no smiles.

![1](https://user-images.githubusercontent.com/5006150/146616511-b6fc0570-c372-4234-940f-0497bc22a4ca.jpg)

Version 0.2.3

![2](https://user-images.githubusercontent.com/5006150/146616539-90729a7f-85ff-48c9-9393-52c04816623e.jpg)

There is Pc smiles.

![3](https://user-images.githubusercontent.com/5006150/146616625-c0fcfd0d-fe3d-4395-ae90-fc2ae79b82c4.jpg)

https://community.marcoborla.it/

The issue seems to be in this file: 
https://github.com/justoverclockl/last-users-posts/blob/main/js/dist/forum.js

A PC smile is inserted so removing it resolve the issue.
Will be problematic if a post start with an image, in this case an empty line will be showed:
![Immagine 2021-12-18 000118](https://user-images.githubusercontent.com/5006150/146617534-c844264a-2cd3-4ebb-b319-3f4021a25b59.jpg)

**Comment by justoverclockl** [comment]
yeah, i've removed the 0.2.3 version some times ago, it was an experiment. the latest and stable is 0.1.7

**Comment by PeopleInside** [comment]
Uh but 0.2.3 take color from Flarum, 0.17 is green :)
The stable version should learn to take Flarum color to adapt to the community colors :)

Thanks

**Comment by justoverclockl** [comment]
yeah i've missed that, it will be fixed in the next version today

**Comment by justoverclockl** [comment]
try now 0.2.4

**Comment by PeopleInside** [comment]
It works.
Only few issue if post start with an image no text is showed in the last post list and I don't know ho you can have discussion large on flarum.it because if I activate the discussion list is showed more shorted because widget on right and left.

**Comment by justoverclockl** [comment]
i will investigate now

**Comment by justoverclockl** [comment]
Fixed in the last version
